### ISSUE TITLE
I have a problem, it says "TypeError: Discord.RichEmbed is not a function"

### ISSUE THREAD

**Issue by saddowner** [finallight1/discord-js-suggestion-bot#1]
I have a problem, it says "TypeError: Discord.RichEmbed is not a function"

**Comment by finallight1** [comment]
Did you open setup.bat first?

**Comment by saddowner** [comment]
Yes

**Comment by finallight1** [comment]
Unzip all of the files to your disk C:" and then open command stroke (cmd.exe) and type in "cd C:/discord-js-suggestion-bot-master after this type in npm install discord.js@11.5.1
This will install the correct version of discord.js in your folder with the bot

**Comment by saddowner** [comment]
- ### **_Thanks, it works now)_**

**Comment by finallight1** [comment]
No problem
